source "https://supermarket.getchef.io"

cookbook "apache2", "= 3.2.2"
cookbook "database", "= 6.1.1"
cookbook "mysql", "= 6.0.28"
cookbook "mysql2_chef_gem", "= 1.0.2"
cookbook "build-essential", "= 2.4.0"
cookbook "iis", "= 6.8.0"
cookbook "tar", "= 2.1.1"
cookbook "openssl", "= 8.1.2"
cookbook "nginx", "= 2.7.6"
cookbook "php", "= 4.6.0"
cookbook "php-fpm", "= 0.6.10"
cookbook "selinux", "= 0.9.0"